### ISSUE TITLE
Empty State Handling

### ISSUE THREAD

**Issue by 7hrn1** [mithraan17/todo-app#1]
https://github.com/mithraan17/todo-app/blob/07d4daa310563030d5d5d0d4c6bfc3a2a935caa2/src/App.js#L18-L22

useEffect saves the todos array to localStorage whenever it changes but only when todos.length > 0. So when all the items are removed from the array and when todos.length is now 0, the empty array will not be saved back to storage. 

How to reproduce this bug:
1. Add a number of tasks
2. Mark all as completed
3. When the list is now empty again, refresh the page
4. Your list will now show the last deleted item instead of being empty :(

**Comment by mithraan17** [comment]
Issue has been resolved by adding an else block to the useEffect hook
