### ISSUE TITLE
Consider Error Message for Empty Input

### ISSUE THREAD

**Issue by 7hrn1** [mithraan17/todo-app#2]
https://github.com/mithraan17/todo-app/blob/07d4daa310563030d5d5d0d4c6bfc3a2a935caa2/src/components/TodoForm.js#L10-L13

Provide feedback to the user if they attempt to add an empty or whitespace-only todo via the if-else. (Input validation and alert prompt)

**Comment by mithraan17** [comment]
resolved with an else block and added a state to pass the error text when an empty input is added
