### ISSUE TITLE
Handling Duplicates 

### ISSUE THREAD

**Issue by Moesha1905** [mithraan17/todo-app#3]
https://github.com/mithraan17/todo-app/blob/07d4daa310563030d5d5d0d4c6bfc3a2a935caa2/src/App.js#L24-L25

Adding validations to the addTodo function to avoid adding the same todos to the list

solution:
if the condition to check if todo is already in the list, prompt alert if it already exist

**Comment by mithraan17** [comment]
const addTodo = (todo) => {
    // Check if the todo already exists in the list
    if (todos.includes(todo)) {
      alert("This todo is already added. Please enter another one.");
      return; 
    }
    // If it's not a duplicate, add it to the list
    setTodos([...todos, todo]);
  };

Thank you for the suggestion , as per request ive added an if else block to the addTodo function with a .includes() function to check if the todo item exists in the todolist array and alert the user to enter another task if it already exists.

Resolved.
