### ISSUE TITLE
Syntax Optimisation

### ISSUE THREAD

**Issue by Moesha1905** [mithraan17/todo-app#4]
https://github.com/mithraan17/todo-app/blob/07d4daa310563030d5d5d0d4c6bfc3a2a935caa2/src/components/TodoItem.js#L5-L11

Define functions outside the JSX syntax for better readability and to avoid creating new render every time

**Comment by mithraan17** [comment]
Thank you for the performance optimization suggestions, as per request I have define the click function outside the JSX
