### ISSUE TITLE
Character Limit

### ISSUE THREAD

**Issue by wenwei1234** [mithraan17/todo-app#6]
https://github.com/mithraan17/todo-app/blob/07d4daa310563030d5d5d0d4c6bfc3a2a935caa2/src/components/TodoForm.js#L16-L27

Can add a character limit for the to-do-items to prevent excessively long items

**Comment by mithraan17** [comment]
Thank you for the suggestion, and issue has been resolved with even an addition to prevent short invalid lists as well
